-- Run once in the project's SQL Editor, after approving the database setup.
-- This creates an EMPTY warehouse. No browser/device data is imported here.
begin;

create table public.warehouse_members (
  user_id uuid primary key references auth.users(id),
  can_import boolean not null default false
);
create table public.warehouse_state (
  singleton boolean primary key default true check (singleton),
  initialized boolean not null default false,
  revision bigint not null default 0,
  imported_at timestamptz,
  imported_by uuid references auth.users(id)
);
insert into public.warehouse_state(singleton) values (true);
create table public.warehouse_locations (
  name text primary key check (name = btrim(name) and char_length(name) between 1 and 40 and name <> '全部位置')
);
create unique index warehouse_location_names on public.warehouse_locations(lower(name));
create table public.warehouse_materials (
  id bigint generated by default as identity primary key check (id between 1 and 9007199254740991),
  name text not null check (char_length(btrim(name)) between 1 and 100),
  spec text not null check (char_length(spec) <= 101),
  stock integer not null check (stock >= 0),
  alert integer check (alert >= 0),
  location text not null references public.warehouse_locations(name),
  detail text not null default '' check (char_length(detail) <= 100),
  version integer not null default 1
);
create unique index warehouse_material_names on public.warehouse_materials(location, lower(btrim(name)));
create table public.warehouse_transactions (
  id uuid primary key default gen_random_uuid(),
  material_id bigint not null references public.warehouse_materials(id),
  material_name text not null,
  unit text not null default '',
  amount integer not null check (amount > 0),
  type text not null check (type in ('增加', '減少')),
  time timestamptz not null default now(),
  reason text not null default '',
  note text not null default '' check (char_length(note) <= 10000),
  user_id uuid references auth.users(id)
);
create index warehouse_transactions_time on public.warehouse_transactions(time);
-- Private idempotency ledger: retries must never apply an adjustment twice.
create table public.warehouse_requests (
  request_id uuid primary key,
  user_id uuid not null references auth.users(id),
  operation text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.warehouse_members enable row level security;
alter table public.warehouse_state enable row level security;
alter table public.warehouse_locations enable row level security;
alter table public.warehouse_materials enable row level security;
alter table public.warehouse_transactions enable row level security;
alter table public.warehouse_requests enable row level security;
revoke all on public.warehouse_members, public.warehouse_state, public.warehouse_locations,
  public.warehouse_materials, public.warehouse_transactions, public.warehouse_requests from anon, authenticated;
revoke all on sequence public.warehouse_materials_id_seq from anon, authenticated;
grant select on public.warehouse_members, public.warehouse_state, public.warehouse_locations,
  public.warehouse_materials, public.warehouse_transactions to authenticated;

create function public.warehouse_has_access() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.warehouse_members where user_id = (select auth.uid()));
$$;
revoke all on function public.warehouse_has_access() from public, anon;
grant execute on function public.warehouse_has_access() to authenticated;
create policy warehouse_member_self on public.warehouse_members for select to authenticated
  using (user_id = (select auth.uid()));
create policy warehouse_state_read on public.warehouse_state for select to authenticated
  using ((select public.warehouse_has_access()));
create policy warehouse_locations_read on public.warehouse_locations for select to authenticated
  using ((select public.warehouse_has_access()));
create policy warehouse_materials_read on public.warehouse_materials for select to authenticated
  using ((select public.warehouse_has_access()));
create policy warehouse_transactions_read on public.warehouse_transactions for select to authenticated
  using ((select public.warehouse_has_access()));

create function public.warehouse_require_access() returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not public.warehouse_has_access() then
    raise exception 'WAREHOUSE_ACCESS_DENIED' using errcode = '42501';
  end if;
end;
$$;
revoke all on function public.warehouse_require_access() from public, anon, authenticated;

create function public.warehouse_snapshot() returns jsonb
language plpgsql security definer set search_path = '' as $$
begin
  perform public.warehouse_require_access();
  -- One statement gives all collections the same MVCC snapshot.
  return (
    select jsonb_build_object(
      'initialized', s.initialized, 'revision', s.revision,
      'canImport', coalesce((select can_import from public.warehouse_members where user_id = auth.uid()), false),
      'materials', coalesce((select jsonb_agg(jsonb_build_object(
        'id', m.id, 'name', m.name, 'spec', m.spec, 'stock', m.stock, 'alert', m.alert,
        'location', m.location, 'detail', m.detail, 'version', m.version) order by m.id)
        from public.warehouse_materials m), '[]'::jsonb),
      'locations', coalesce((select jsonb_agg(name order by name) from public.warehouse_locations), '[]'::jsonb),
      'transactions', coalesce((select jsonb_agg(jsonb_build_object(
        'id', t.id, 'materialId', t.material_id, 'materialName', t.material_name, 'unit', t.unit,
        'amount', t.amount, 'type', t.type, 'time', t.time, 'reason', t.reason, 'note', t.note)
        order by t.time, t.id) from public.warehouse_transactions t), '[]'::jsonb)
    ) from public.warehouse_state s where s.singleton
  );
end;
$$;
revoke all on function public.warehouse_snapshot() from public, anon;
grant execute on function public.warehouse_snapshot() to authenticated;

create function public.warehouse_mutate(p_request_id uuid, p_operation text, p_payload jsonb) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_state public.warehouse_state%rowtype;
  v_request public.warehouse_requests%rowtype;
  v_item public.warehouse_materials%rowtype;
  v_json jsonb;
  v_name text;
  v_amount integer;
  v_id bigint;
begin
  perform public.warehouse_require_access();
  if p_request_id is null or p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'WAREHOUSE_INVALID_INPUT';
  end if;
  -- Serialize writes, including first import, so two devices cannot overwrite each other.
  select * into strict v_state from public.warehouse_state where singleton for update;
  select * into v_request from public.warehouse_requests where request_id = p_request_id;
  if found then
    if v_request.user_id <> auth.uid() or v_request.operation <> p_operation or v_request.payload <> p_payload then
      raise exception 'WAREHOUSE_REQUEST_CONFLICT';
    end if;
    return public.warehouse_snapshot();
  end if;

  if p_operation = 'import_phone' then
    if not (select can_import from public.warehouse_members where user_id = auth.uid()) then
      raise exception 'WAREHOUSE_IMPORT_NOT_ALLOWED' using errcode = '42501';
    end if;
    if v_state.initialized or exists (select 1 from public.warehouse_materials) then
      raise exception 'WAREHOUSE_ALREADY_INITIALIZED';
    end if;
    if p_payload->>'source' is distinct from 'phone'
      or p_payload->>'schemaVersion' is distinct from '1'
      or jsonb_typeof(p_payload->'materials') is distinct from 'array'
      or jsonb_typeof(p_payload->'transactions') is distinct from 'array'
      or jsonb_typeof(p_payload->'locations') is distinct from 'array' then
      raise exception 'WAREHOUSE_INVALID_IMPORT';
    end if;
    if jsonb_array_length(p_payload->'materials') < 1 then raise exception 'WAREHOUSE_EMPTY_IMPORT'; end if;
    for v_json in select value from jsonb_array_elements(p_payload->'locations') loop
      if jsonb_typeof(v_json) <> 'string' then raise exception 'WAREHOUSE_INVALID_IMPORT'; end if;
      insert into public.warehouse_locations(name) values (btrim(v_json #>> '{}')) on conflict (name) do nothing;
    end loop;
    for v_json in select value from jsonb_array_elements(p_payload->'materials') loop
      if jsonb_typeof(v_json->'id') is distinct from 'number'
        or jsonb_typeof(v_json->'stock') is distinct from 'number'
        or jsonb_typeof(v_json->'name') is distinct from 'string'
        or jsonb_typeof(v_json->'spec') is distinct from 'string'
        or jsonb_typeof(v_json->'location') is distinct from 'string' then
        raise exception 'WAREHOUSE_INVALID_IMPORT';
      end if;
      insert into public.warehouse_materials(id, name, spec, stock, alert, location, detail)
        values ((v_json->>'id')::bigint, btrim(v_json->>'name'), v_json->>'spec', (v_json->>'stock')::integer,
          (v_json->>'alert')::integer, btrim(v_json->>'location'), coalesce(v_json->>'detail', ''));
    end loop;
    -- Identity must continue above legacy IDs instead of colliding with the imported materials.
    perform setval('public.warehouse_materials_id_seq'::regclass,
      (select max(id) from public.warehouse_materials), true);
    for v_json in select value from jsonb_array_elements(p_payload->'transactions') loop
      insert into public.warehouse_transactions(material_id, material_name, unit, amount, type, time, reason, note)
        select (v_json->>'materialId')::bigint, coalesce(v_json->>'materialName', m.name),
          coalesce(v_json->>'unit', split_part(m.spec, '／', 2)), (v_json->>'amount')::integer,
          v_json->>'type', (v_json->>'time')::timestamptz,
          coalesce(v_json->>'reason', ''), coalesce(v_json->>'note', '')
        from public.warehouse_materials m where m.id = (v_json->>'materialId')::bigint;
      if not found then raise exception 'WAREHOUSE_ORPHAN_TRANSACTION'; end if;
    end loop;
    update public.warehouse_state set initialized = true, imported_at = now(), imported_by = auth.uid() where singleton;
  else
    if not v_state.initialized then raise exception 'WAREHOUSE_NOT_INITIALIZED'; end if;
    if p_operation = 'add_location' then
      v_name := btrim(p_payload->>'name');
      if v_name is null then raise exception 'WAREHOUSE_INVALID_INPUT'; end if;
      insert into public.warehouse_locations(name) values (v_name);
    elsif p_operation = 'save_material' then
      if char_length(btrim(coalesce(p_payload->>'name', ''))) not between 1 and 100
        or char_length(btrim(coalesce(p_payload->>'category', ''))) not between 1 and 80
        or char_length(btrim(coalesce(p_payload->>'unit', ''))) not between 1 and 20
        or p_payload->>'alert' is null then raise exception 'WAREHOUSE_INVALID_INPUT'; end if;
      if p_payload->>'id' is null then
        insert into public.warehouse_materials(name, spec, stock, alert, location, detail) values (
          btrim(p_payload->>'name'), btrim(p_payload->>'category') || '／' || btrim(p_payload->>'unit'),
          (p_payload->>'stock')::integer, (p_payload->>'alert')::integer, p_payload->>'location', coalesce(p_payload->>'detail', ''));
      else
        v_id := (p_payload->>'id')::bigint;
        select * into v_item from public.warehouse_materials where id = v_id for update;
        if not found then raise exception 'WAREHOUSE_MATERIAL_NOT_FOUND'; end if;
        if v_item.version is distinct from (p_payload->>'version')::integer then
          raise exception 'WAREHOUSE_EDIT_CONFLICT';
        end if;
        update public.warehouse_materials set name = btrim(p_payload->>'name'),
          spec = btrim(p_payload->>'category') || '／' || btrim(p_payload->>'unit'),
          alert = (p_payload->>'alert')::integer, location = p_payload->>'location',
          detail = coalesce(p_payload->>'detail', ''), version = version + 1 where id = v_id;
      end if;
    elsif p_operation = 'adjust_stock' then
      v_id := (p_payload->>'materialId')::bigint;
      v_amount := (p_payload->>'amount')::integer;
      if v_amount is null or v_amount = 0
        or p_payload->>'reason' is null or p_payload->>'reason' not in ('入庫補貨', '維修使用')
        or char_length(coalesce(p_payload->>'note', '')) > 2000 then raise exception 'WAREHOUSE_INVALID_INPUT'; end if;
      select * into v_item from public.warehouse_materials where id = v_id for update;
      if not found then raise exception 'WAREHOUSE_MATERIAL_NOT_FOUND'; end if;
      if v_item.stock::bigint + v_amount < 0 then raise exception 'WAREHOUSE_INSUFFICIENT_STOCK'; end if;
      update public.warehouse_materials set stock = stock + v_amount, version = version + 1 where id = v_id;
      insert into public.warehouse_transactions(material_id, material_name, unit, amount, type, reason, note, user_id)
        values (v_id, v_item.name, split_part(v_item.spec, '／', 2), abs(v_amount),
          case when v_amount > 0 then '增加' else '減少' end, p_payload->>'reason', coalesce(p_payload->>'note', ''), auth.uid());
    else
      raise exception 'WAREHOUSE_INVALID_OPERATION';
    end if;
  end if;
  update public.warehouse_state set revision = revision + 1 where singleton;
  insert into public.warehouse_requests(request_id, user_id, operation, payload) values (p_request_id, auth.uid(), p_operation, p_payload);
  return public.warehouse_snapshot();
end;
$$;
revoke all on function public.warehouse_mutate(uuid, text, jsonb) from public, anon;
grant execute on function public.warehouse_mutate(uuid, text, jsonb) to authenticated;
commit;
